### ISSUE TITLE
LaTeX sources?

### ISSUE THREAD

**Issue by giovanniberti** [w00zie/Appunti#1]
Can you make LaTeX sources available? :smiley:

**Comment by w00zie** [comment]
Ciao ragazzi, mi sono accorto solo adesso di questa issue! Scusate.
Ho aggiunto i sorgenti, se volete ancora fare delle modifiche vi sarei grato se forkaste/clonaste la repo per poi farmi una pull request a lavoro ultimato, in modo da mantenere una versione aggiornata anche quì.

Scusate ancora, ciao!

**Comment by giovanniberti** [comment]
Grazie mille!
